version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      spring:
        patterns: ["org.springframework*"]
      openapi-tooling:
        patterns: ["org.openapitools*", "io.swagger*", "com.atlassian.oai*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
